### ISSUE TITLE
PHP ERROR when viewing QSO without lat & log

### ISSUE THREAD

**Issue by M0JGX** [magicbug/Cloudlog#1058]
PHP ERROR when viewing QSO without lat & log

Undefined Index lat 
Undefined Index long    Lines 441 & 441

Would suggest using isset as a fix

Something like 
if (isset($result['lat'])) {$lat = $result['lat'];}
if (isset($result['long'])) {$lng = $result['long'];}

I'm sure you can come up with something better

![image](https://user-images.githubusercontent.com/85508750/121052428-47583000-c7b2-11eb-83f3-965c45fd86f8.png)

**Comment by magicbug** [comment]
Should be resolved

**Comment by Jaif** [comment]
This issue is unfortunately not resolved yet. I also get errors when viewing a certain QSO.
![image](https://user-images.githubusercontent.com/6058039/173770623-c16e9dbe-308d-4a45-b0fa-7c195e0fbdc2.png)

It seems to also break the dashboard map pointers, the JSON data returned from index.php/logbook/qso_map/25 contains PHP error HTML which makes it invalid as JSON.
