### ISSUE TITLE
Current Cat.php doesn't work with CloudlogCAT

### ISSUE THREAD

**Issue by ofadam** [magicbug/Cloudlog#1236]
Since this commit (https://github.com/magicbug/Cloudlog/commit/b18e1013f3a121d07c7b4f97c5f401b7ba64fca0#diff-08a03f5c387c214d6aa8dcaeb4c3945b0f860ec78af68bda38b0a2b8dfe13cb6), CloudlogCAT hasn't been able to sync with Cloudlog despite correct URL and API key. It appears that the timestamp addition makes CloudlogCAT incompatible?

**Comment by magicbug** [comment]
This should be resolved now the STATUS now checks based on UTC rather than SQL servers local time

**Comment by ofadam** [comment]
Just tested and the change doesn't seem to fix things. Happy to help try any adjustments outside of a formal commit.

(I'm running Cloudlog on a DigitalOcean instance, which apparently defaults to local time and not UTC – I can probably change this to fix the issue, but might come up again for those installing fresh.)

**Comment by magicbug** [comment]
Can you confirm the entry inside the cat table is utc time?

**Comment by magicbug** [comment]
Found a few more bits of code that need changing so that will get done later.

**Comment by ofadam** [comment]
In case this is helpful, I did change my web hosting server to UTC instead of local time. Now, CloudlogCAT syncs at first, then errors – with the result in the "Hardware Interfaces" panel:

<img width="987" alt="Screen Shot 2022-01-04 at 12 44 49 PM" src="https://user-images.githubusercontent.com/5504940/148108571-d8007073-c475-4a79-8e09-fae443cac6d7.png">

**Comment by magicbug** [comment]
OK thats interesting so i'm using https://github.com/magicbug/CloudlogCAT/releases/download/1.3.5/CloudlogCAT.zip

![Capture](https://user-images.githubusercontent.com/84308/148135095-44fcf663-e630-43f9-a566-216b0b3bfd83.PNG)

Of course this servers running on UTC.

**Comment by ofadam** [comment]
All is well with today's commit! Thanks so much.
