### ISSUE TITLE
Error on Distances Worked page

### ISSUE THREAD

**Issue by ofadam** [magicbug/Cloudlog#1360]
When using the latest version of the "station_logbook" branch, I get an "undefined" error in red on the Distances Worked page regardless of the band selected.

**Comment by AndreasK79** [comment]
I just noticed this yesterday as well. I pushed a fix. Pull the latest code and report back if it works.

**Comment by ofadam** [comment]
Just pulled the latest code and I'm still getting the error.

**Comment by AndreasK79** [comment]
Ok. This solved my problem. Can you go in devtools and network. Then click plot. You will se a call to get distances. Click on it, and see if you se an error message.

**Comment by ofadam** [comment]
Loads of errors! Here are the first of many: 

`<h4>A PHP Error was encountered</h4>

<p>Severity: Warning</p>
<p>Message:  A non-numeric value encountered</p>
<p>Filename: models/Distances_model.php</p>
<p>Line Number: 70</p>

</div><div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">

<h4>A PHP Error was encountered</h4>

<p>Severity: Notice</p>
<p>Message:  Undefined offset: 260</p>
<p>Filename: models/Distances_model.php</p>
<p>Line Number: 73</p>

</div><div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">

<h4>A PHP Error was encountered</h4>

<p>Severity: Notice</p>
<p>Message:  Trying to access array offset on value of type null</p>
<p>Filename: models/Distances_model.php</p>
<p>Line Number: 73</p>

</div><div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">

<h4>A PHP Error was encountered</h4>

<p>Severity: Notice</p>
<p>Message:  Undefined offset: 260</p>
<p>Filename: models/Distances_model.php</p>
<p>Line Number: 73</p>

</div><div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">

<h4>A PHP Error was encountered</h4>

<p>Severity: Notice</p>
<p>Message:  Undefined index: count</p>
<p>Filename: models/Distances_model.php</p>
<p>Line Number: 73</p>

</div><div style="border:1px solid #990000;padding-left:20px;margin:0 0 10px 0;">

<h4>A PHP Error was encountered</h4>

<p>Severity: Notice</p>
<p>Message:  Undefined index: callcount</p>
<p>Filename: models/Distances_model.php</p>
<p>Line Number: 75</p>`

**Comment by AndreasK79** [comment]
@ofadam thanks. Another bug it seems. I think I managed to reproduce it here. It has to do with 2 or more stations locations, where one of them doesn't have any QSOs on the band chosen. I'll get back to you when I have a fix you can try,

**Comment by AndreasK79** [comment]
@ofadam give the latest commit on station_logbooks a go, and report back the result.

**Comment by ofadam** [comment]
That did the trick! Thanks so much.

**Comment by magicbug** [comment]
@AndreasK79 HF fixed however Sats still broken

**Comment by AndreasK79** [comment]
@ofadam great.

@magicbug can't reproduce here. Can you dig up some error messages? I can plot "All" fine here.

**Comment by magicbug** [comment]
When I do "SAT" "ALL" and click plot it returns 

{
"Error": "No QSOs found to plot."
}

Which cant be right as there's 11946q in the logbook!

**Comment by AndreasK79** [comment]
That doesn't make sense. Though I can't really tell why it's doing this in your case.

That message is returned two places in Distances_model: line 15 and line 59. I'm not sure I can manage to figure this one out without remote debugging, or you take a look yourself.

**Comment by magicbug** [comment]
I'll have a poke around see if I can fix it
