### ISSUE TITLE
Serial don't save with space

### ISSUE THREAD

**Issue by Stiles96** [magicbug/Cloudlog#2025]
**Describe the bug**
Received Serials in Contest Mode won't be saved, if you are using space to jump the next field. Missing a trim() before convert?

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Contest Log
2. Log with serial
3. Jump to next field by using the space
4. Save QSO (Enter doesn't work)

**Expected behaviour**
Serial will be saved.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/51234422/222966245-6f493a36-cf5a-4716-84f1-1ea85faf03c8.png)

Missing received Serial:
![grafik](https://user-images.githubusercontent.com/51234422/222965167-87dcbe1d-b4ea-4afd-8cb9-e2f9b1e6a402.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Firefox
 - Version 110

**Comment by AndreasK79** [comment]
Enter was only triggered when in received exchange. Guess it was never expanded when adding more exchanges. I've pushed a change to the dev branch so that either serial or gridsquare received, logs qso when hitting enter.

**Comment by Stiles96** [comment]
The Issue isn't fixed. The issue is the space at the end of the serial. You can save the QSO, but without the serial. (Step 3, You see the space also in the screenshot).

**Comment by AndreasK79** [comment]
Can't reproduce that problem here. Received serial saves here after hitting space in serial, then entering grid and hitting enter (or clicking button).

**Comment by AndreasK79** [comment]
It might be a problem related to differences in database setup, and how strict things are.

Can you edit the source code and try to add a trim like this?

logbook_model.php, line 23:
      `$srx = $this->input->post('exch_serial_r') == '' ? null : trim($this->input->post('exch_serial_r'));`

**Comment by Stiles96** [comment]
I tested and it doesn't work.
I debugged also the session and can see that the serial isn't transmitted by Firefox itself:
![image](https://user-images.githubusercontent.com/51234422/229446748-0a33d552-80f1-4cbd-88cc-5dc9d8a1d950.png)

In Chrome it works very well.

**Comment by AndreasK79** [comment]
Yes, Firefox seems to not work all the time. I got it to not save the serial received, but some times it saved it as well. I have no clue on what is going on regarding this, so this is not something I can fix.

**Comment by AndreasK79** [comment]
I had a discussion with @phl0, and it seems you were right regarding the space. In exchange, space is not written, but this was not implemented in the received serial. I pushed a fix that implements this. Seems to fix the issue you reported.

**Comment by phl0** [comment]
Tested and fix confirmed on my end. Pls test and report :)

**Comment by Stiles96** [comment]
It works! Good work.
